[project]
name = "report-execution"
version = "0.1.0"
description = "A FastAPI server for the management and execution of both standard and custom reports."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "pydantic>=2.12.5",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.0",
]
